import {
  Anchor,
  Baby,
  Backpack,
  Bike,
  Book,
  Briefcase,
  Camera,
  Car,
  Coffee,
  Compass,
  Dog,
  Droplet,
  Dumbbell,
  Fish,
  Flame,
  Hammer,
  Heart,
  Home,
  ListChecks,
  Luggage,
  Mountain,
  Music,
  PaintRoller,
  Palmtree,
  Package,
  Plane,
  Sailboat,
  Scissors,
  Shirt,
  ShoppingCart,
  Snowflake,
  Sparkles,
  Stethoscope,
  Sun,
  Tent,
  Tractor,
  Trees,
  UtensilsCrossed,
  Waves,
  Wine,
  Wrench,
  type LucideIcon
} from 'lucide-react'

// Kept in sync with server/checklists.ts's CHECKLIST_ICON_SET. A fixed,
// curated set rather than the full Lucide library: keeps the picker to one
// scrollable grid instead of a searchable directory of 1500+ names.
export const CHECKLIST_ICONS: Record<string, LucideIcon> = {
  Waves,
  Sailboat,
  Anchor,
  Fish,
  Droplet,
  Tent,
  Mountain,
  Trees,
  Palmtree,
  Compass,
  Backpack,
  Snowflake,
  Sun,
  Flame,
  Dumbbell,
  Bike,
  Car,
  Plane,
  Luggage,
  Home,
  Wrench,
  Hammer,
  Tractor,
  PaintRoller,
  Scissors,
  Package,
  ShoppingCart,
  UtensilsCrossed,
  Coffee,
  Wine,
  Briefcase,
  Book,
  Music,
  Camera,
  Baby,
  Dog,
  Heart,
  Stethoscope,
  Sparkles,
  Shirt,
  ListChecks
}

export const CHECKLIST_ICON_NAMES = Object.keys(CHECKLIST_ICONS)

export const DEFAULT_CHECKLIST_ICON = 'ListChecks'

export function checklistIcon(name: string | null | undefined): LucideIcon {
  return (name && CHECKLIST_ICONS[name]) || CHECKLIST_ICONS[DEFAULT_CHECKLIST_ICON]
}
